export const freeAssets = [
  {
    id: "1",
    title: "Anime Character Pack",
    creator: "Salman Khan",
    image: "/images/free/free-1.jpg",
    rating: 4.9,
    downloads: "12.5K",
  },
  {
    id: "2",
    title: "Fantasy Background",
    creator: "Pixel Forge",
    image: "/images/free/free-2.jpg",
    rating: 5.0,
    downloads: "18.2K",
  },
  {
    id: "3",
    title: "UI Starter Kit",
    creator: "Dream Pixels",
    image: "/images/free/free-3.jpg",
    rating: 4.8,
    downloads: "9.3K",
  },
  {
    id: "4",
    title: "Forest Props",
    creator: "AK Studio",
    image: "/images/free/free-4.jpg",
    rating: 4.7,
    downloads: "6.1K",
  },
  {
    id: "5",
    title: "Cute Animals Pack",
    creator: "Nova Design",
    image: "/images/free/free-5.jpg",
    rating: 4.9,
    downloads: "14.7K",
  },
  {
    id: "6",
    title: "Magic Effects",
    creator: "Animation Craft",
    image: "/images/free/free-6.jpg",
    rating: 4.8,
    downloads: "8.4K",
  },
];
