import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Poppins } from "next/font/google";
import "./globals.css";
import { ToastProvider } from "@/components/common/toast/ToastProvider";
import { AssetModalProvider } from "@/components/asset-modal/context/AssetModalProvider";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-poppins",
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased ${poppins.variable}`}
    >
      <body className="min-h-full flex flex-col">
        <ToastProvider>
          <AssetModalProvider>
            {children}
          </AssetModalProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
