export const creators = [
  {
    id: "1",
    name: "Salman Khan",
    avatar: "/images/avatar-1.jpg",
    profession: "2D Character Artist",
    rating: 4.9,
    assets: 1245,
    followers: "12K",
    downloads: "185K",
    following: false,
  },
  {
    id: "2",
    name: "Pixel Forge",
    avatar: "/images/avatar-2.jpg",
    profession: "Animation Studio",
    rating: 5.0,
    assets: 862,
    followers: "8K",
    downloads: "143K",
    following: true,
  },
  {
    id: "3",
    name: "Anime Craft",
    avatar: "/images/avatar-3.jpg",
    profession: "Illustrator",
    rating: 4.8,
    assets: 413,
    followers: "5K",
    downloads: "81K",
    following: false,
  },
  {
    id: "4",
    name: "Nova Studio",
    avatar: "/images/avatar-4.jpg",
    profession: "Background Artist",
    rating: 4.9,
    assets: 295,
    followers: "4K",
    downloads: "52K",
    following: false,
  },
  {
    id: "5",
    name: "Dream Pixels",
    avatar: "/images/avatar-5.jpg",
    profession: "Game Artist",
    rating: 4.7,
    assets: 188,
    followers: "2K",
    downloads: "35K",
    following: false,
  },
  {
    id: "6",
    name: "Aster Labs",
    avatar: "/images/avatar-6.jpg",
    profession: "Concept Artist",
    rating: 5.0,
    assets: 620,
    followers: "7K",
    downloads: "120K",
    following: true,
  },
];