export const assets = [
  {
    id: "1",
    title: "Anime Warrior Girl",
    creator: "Animark Studio",
    image: "/images/assets/1.jpg",
    price: 799,
    originalPrice: 1299,
    discount: 38,
    rating: 4.9,
    totalReviews: 184,
  },
  {
    id: "2",
    title: "Cyber Ninja",
    creator: "Pixel Forge",
    image: "/images/assets/2.jpg",
    price: 599,
    originalPrice: 999,
    discount: 40,
    rating: 4.8,
    totalReviews: 152,
  },
  {
    id: "3",
    title: "Fantasy Mage",
    creator: "Anime Craft",
    image: "/images/assets/3.jpg",
    price: 949,
    originalPrice: 1499,
    discount: 37,
    rating: 5.0,
    totalReviews: 221,
  },
  {
    id: "4",
    title: "School Girl",
    creator: "Creative Box",
    image: "/images/assets/4.jpg",
    price: 399,
    originalPrice: 699,
    discount: 43,
    rating: 4.7,
    totalReviews: 88,
  },
  {
    id: "5",
    title: "Dark Samurai",
    creator: "Animark Studio",
    image: "/images/assets/5.jpg",
    price: 899,
    originalPrice: 1399,
    discount: 36,
    rating: 4.9,
    totalReviews: 201,
  },
  {
    id: "6",
    title: "Cute Chibi Pack",
    creator: "Pixel Forge",
    image: "/images/assets/6.jpg",
    price: 299,
    originalPrice: 499,
    discount: 40,
    rating: 4.8,
    totalReviews: 144,
  },
  {
    id: "7",
    title: "Space Soldier",
    creator: "Creative Box",
    image: "/images/assets/7.jpg",
    price: 1199,
    originalPrice: 1799,
    discount: 33,
    rating: 4.9,
    totalReviews: 118,
  },
  {
    id: "8",
    title: "Elf Princess",
    creator: "Anime Craft",
    image: "/images/assets/8.jpg",
    price: 699,
    originalPrice: 999,
    discount: 30,
    rating: 4.7,
    totalReviews: 106,
  },
  {
    id: "9",
    title: "Knight Collection",
    creator: "Animark Studio",
    image: "/images/assets/9.jpg",
    price: 999,
    originalPrice: 1499,
    discount: 34,
    rating: 5.0,
    totalReviews: 233,
  },
  {
    id: "10",
    title: "Pirate Captain",
    creator: "Pixel Forge",
    image: "/images/assets/10.jpg",
    price: 549,
    originalPrice: 899,
    discount: 39,
    rating: 4.8,
    totalReviews: 132,
  },
  {
    id: "11",
    title: "Sci-fi Robot",
    creator: "Creative Box",
    image: "/images/assets/11.jpg",
    price: 849,
    originalPrice: 1299,
    discount: 35,
    rating: 4.9,
    totalReviews: 174,
  },
  {
    id: "12",
    title: "Royal Queen",
    creator: "Anime Craft",
    image: "/images/assets/12.jpg",
    price: 749,
    originalPrice: 1099,
    discount: 32,
    rating: 4.8,
    totalReviews: 145,
  },
];
